### ISSUE TITLE
Fix for the example config file

### ISSUE THREAD

**Issue by kerma** [flyinprogrammer/aws-sso-fetcher#1]
Ended up here from https://github.com/terraform-providers/terraform-provider-aws/issues/10851#issuecomment-626104832

Nice workaround 👍 

However, there is a small problem in the example given in the README. The issue comes down to INI file implementations in different languages. The current example works with Python (aws cli), but not with Go AWS SDK. Their [parser](https://pkg.go.dev/github.com/aws/aws-sdk-go/internal/ini?tab=doc) does not pick up the first profile parameter. SDK itself "eats" the error message, so tools depending on it (terraform, aws-iam-authenticator) fail without much help. Took some time to get to the bottom of this. 

The following (no quotes) seems to work for both boto based things and aws-sdk-go: 

```
[profile wrap_acme_dev]
credential_process = /Users/alice/bin/aws-sso-fetcher acme_dev
```

**Comment by flyinprogrammer** [comment]
Thanks for reporting this, I hadn't run into it yet!
