### ISSUE TITLE
Wrapping profile not needed

### ISSUE THREAD

**Issue by benkehoe** [flyinprogrammer/aws-sso-fetcher#2]
Your README has this:
```ini
[profile acme_dev]
sso_start_url = https://acme.awsapps.com/start/
sso_region = us-east-2
sso_account_id = 0123456789
sso_role_name = AWSAdministratorAccess
region = us-east-2
output = json

[profile wrap_acme_dev]
credential_process = /Users/alice/bin/aws-sso-fetcher acme_dev
region = us-west-1
output = json
```

but I believe it should still work if you fold it together:

```init
[profile acme_dev]
credential_process = /Users/alice/bin/aws-sso-fetcher acme_dev

sso_start_url = https://acme.awsapps.com/start/
sso_region = us-east-2
sso_account_id = 0123456789
sso_role_name = AWSAdministratorAccess
region = us-west-1
output = json
```

The CLI v2 prefers the SSO config over credential_process, so it won't run it (good), and the SDKs will just pick up the credential_process and ignore the SSO config.

**Comment by flyinprogrammer** [comment]
huh that's clever, i'll play with that tonight

**Comment by z0mbix** [comment]
This works for me with terraform/go as long as I set: `export AWS_SDK_LOAD_CONFIG=1`

**Comment by benkehoe** [comment]
I don't think that's dependent on this tool; for some reason, the Go SDK doesn't automatically use `~/.aws/config` in its credential sources

**Comment by sidewinder12s** [comment]
Can also confirm this appears to work fine with Terraform & the `AWS_SDK_LOAD_CONFIG` environment variable (and did not work without the SDK_LOAD variable)

**Comment by flyinprogrammer** [comment]
updated the README to remove the wrapper language, and to document needed to set `AWS_SDK_LOAD_CONFIG` - let me know if there's more that's needed.
